# Generated by Django 4.0.4 on 2022-05-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_name_alter_account_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='nickname',
        ),
    ]
