# Generated by Django 4.0.4 on 2022-05-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_name_alter_account_table'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apple',
            new_name='OAuthApple',
        ),
        migrations.RenameField(
            model_name='oauthapple',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterModelTable(
            name='oauthapple',
            table='oauth_apple',
        ),
    ]
